### ISSUE TITLE
Freenove with React-Native Module

### ISSUE THREAD

**Issue by kvlknctk** [Freenove/Freenove_App_for_Android#1]
Hi, 
I want to remote controll this car with react-native. I wonder this project code. Is it open source? 
I want to make native module for rn. Is this possible? 

Best regards.

**Comment by SuhaylZhao** [comment]
Hi,

We have no plans to open Android app source code at present. But we can provide communication protocols for these products. If you need it, please go through support@freenove.com contact us.

In addition, our app for IOS is also under internal testing and will be officially released soon.

Thanks.
